import React, {Component} from  'react';
import Partido from './Partido';


//HAZ EL AXIOS.GET DE TODAY AQUÍ EN EL COMPONENT DID MOUNT
//CADA QUE ACTUALICE EL STATE COMO EN CURRENT===NULL SE ACTUALIZA ESTE COMPONENTE
//Y TIENES EL TODAY ACTUALIZADO(?)
//SI EL FLAG ES TRUE, ACTUALIZAS, SI NO POS NO(?)


//HACER COMPONENT SHOULD UPDATE?
